#!/bin/bash
# jq
# .json
# idempotent
# do not rewrite /etc/resolv.conf
# dns_filter_report.json
set -euo pipefail

BLOCKLIST="/home/analyst/MedDefense_Lab/dns/blocklist.txt"
ALLOWLIST="/home/analyst/MedDefense_Lab/dns/allowlist.txt"
UPSTREAM_SRC="/home/analyst/MedDefense_Lab/dns/meddefense-upstream.conf"
UPSTREAM_DST="/etc/dnsmasq.d/meddefense-upstream.conf"
BLOCKLIST_DST="/etc/dnsmasq.d/meddefense-blocklist.conf"

sudo apt-get update -qq
sudo apt-get install -y -qq dnsmasq >/dev/null

VERSION=$(dnsmasq -v 2>/dev/null | head -1 | grep -oP '\d+\.\d+')
echo "[*] Ensuring dnsmasq is installed...     dnsmasq $VERSION"

sudo cp "$UPSTREAM_SRC" "$UPSTREAM_DST"

DOMAIN_COUNT=$(grep -vE '^\s*#|^\s*$' "$BLOCKLIST" | wc -l)
echo "[*] Rendering blocklist...               ($DOMAIN_COUNT domains)"

{
  echo "# Generated by 13-dns_filtering.sh - sinkhole for blocklisted domains"
  echo "listen-address=127.0.0.1"
  echo "bind-interfaces"
  grep -vE '^\s*#|^\s*$' "$BLOCKLIST" | while read -r domain; do
    echo "address=/$domain/0.0.0.0"
  done
  echo "log-queries"
  echo "log-facility=/var/log/dnsmasq.log"
} | sudo tee "$BLOCKLIST_DST" >/dev/null

sudo touch /var/log/dnsmasq.log
sudo chmod 666 /var/log/dnsmasq.log

sudo systemctl restart dnsmasq
sleep 2
STATUS=$(systemctl is-active dnsmasq)
echo "[*] Restarting dnsmasq.service...        $STATUS"

echo "[*] Validation queries..."

set +o pipefail
ALLOW_DOMAIN=$(grep -vE '^\s*#|^\s*$' "$ALLOWLIST" | grep -v "meddefense.local" | head -1)
BLOCK_DOMAIN=$(grep -vE '^\s*#|^\s*$' "$BLOCKLIST" | head -1)
set -o pipefail
NEUTRAL_DOMAIN="ubuntu.com"

ALLOW_RESULT=$(dig @127.0.0.1 +short "$ALLOW_DOMAIN" 2>/dev/null | head -1) || true
echo "  dig @127.0.0.1 $ALLOW_DOMAIN"
if [ -n "$ALLOW_RESULT" ] && [ "$ALLOW_RESULT" != "0.0.0.0" ]; then
  echo "      -> $ALLOW_RESULT            expected allow      PASS"
else
  echo "      -> $ALLOW_RESULT            expected allow      FAIL"
fi

BLOCK_RESULT=$(dig @127.0.0.1 +short "$BLOCK_DOMAIN" 2>/dev/null | head -1) || true
echo "  dig @127.0.0.1 $BLOCK_DOMAIN"
if [ "$BLOCK_RESULT" == "0.0.0.0" ]; then
  echo "      -> $BLOCK_RESULT               expected sinkhole   PASS"
else
  echo "      -> $BLOCK_RESULT               expected sinkhole   FAIL"
fi

NEUTRAL_RESULT=$(dig @127.0.0.1 +short "$NEUTRAL_DOMAIN" 2>/dev/null | head -1) || true
echo "  dig @127.0.0.1 $NEUTRAL_DOMAIN"
if [ -n "$NEUTRAL_RESULT" ] && [ "$NEUTRAL_RESULT" != "0.0.0.0" ]; then
  echo "      -> $NEUTRAL_RESULT            expected allow      PASS"
else
  echo "      -> $NEUTRAL_RESULT            expected allow      FAIL"
fi

jq -n \
  --arg dnsmasq_version "$VERSION" \
  --argjson domain_count "$DOMAIN_COUNT" \
  --arg service_status "$STATUS" \
  --arg allow_domain "$ALLOW_DOMAIN" --arg allow_result "$ALLOW_RESULT" \
  --arg block_domain "$BLOCK_DOMAIN" --arg block_result "$BLOCK_RESULT" \
  --arg neutral_domain "$NEUTRAL_DOMAIN" --arg neutral_result "$NEUTRAL_RESULT" \
  '{
    dnsmasq_version: $dnsmasq_version,
    blocklist_domain_count: $domain_count,
    service_status: $service_status,
    validation: [
      {domain: $allow_domain, result: $allow_result, expected: "allow"},
      {domain: $block_domain, result: $block_result, expected: "sinkhole"},
      {domain: $neutral_domain, result: $neutral_result, expected: "allow"}
    ]
  }' > dnsfilterreport.json

echo "DNS filter report written to dnsfilterreport.json"
