table inet meddefense {

  set dmz_net {
    type ipv4_addr
    flags interval
    elements = { 10.10.10.0/24 }
  }

  set internal_net {
    type ipv4_addr
    flags interval
    elements = { 10.20.20.0/24 }
  }

  set mgmt_net {
    type ipv4_addr
    flags interval
    elements = { 10.30.30.0/24 }
  }

  set meddev_net {
    type ipv4_addr
    flags interval
    elements = { 10.40.40.0/24 }
  }

  chain input {
    type filter hook input priority 0; policy drop;

    ct state established,related accept
    iifname "lo" accept

    icmp type {
      echo-request,
      echo-reply,
      destination-unreachable,
      time-exceeded
    } accept

    ip saddr @mgmt_net tcp dport 22 accept comment "MGMT_SSH_STANDING"
    ip saddr 10.0.2.2 tcp dport 22 accept comment "LAB_SSH_SAFETY"
    ip saddr 10.0.2.2 tcp dport 22 accept comment "SAFETY_ACTIVE_SSH"

    udp dport 53 accept comment "LOCAL_DNS_UDP"
    tcp dport 53 accept comment "LOCAL_DNS_TCP"

    log prefix "meddefense-input-drop: " drop
  }

  chain forward {
    type filter hook forward priority 0; policy drop;

    ct state established,related accept
    ip saddr @mgmt_net ip daddr @internal_net tcp dport 22 accept comment "FLOW_1"
    ip saddr @mgmt_net ip daddr @dmz_net tcp dport 22 accept comment "FLOW_2"
    ip saddr @internal_net ip daddr @internal_net tcp dport 443 accept comment "FLOW_3"
    ip saddr @internal_net ip daddr @internal_net tcp dport 3306 accept comment "FLOW_4"
    ip saddr @dmz_net ip daddr @internal_net tcp dport 3306 accept comment "FLOW_5"
    ip saddr @meddev_net ip daddr @internal_net tcp dport 4242 accept comment "FLOW_6"
    ip saddr @meddev_net ip daddr @internal_net tcp dport 443 accept comment "FLOW_7"
     ip daddr @mgmt_net udp dport 53 accept comment "FLOW_8"
     ip daddr @mgmt_net tcp dport 53 accept comment "FLOW_9"
    ip saddr @mgmt_net ip daddr @meddev_net tcp dport 22 accept comment "FLOW_10"
    ip saddr @mgmt_net ip daddr @meddev_net tcp dport 4242 accept comment "FLOW_11"
    ip saddr @dmz_net ip daddr @meddev_net drop comment "FLOW_12"
    ip saddr @internal_net ip daddr @meddev_net drop comment "FLOW_13"
    ip saddr @meddev_net ip daddr @dmz_net drop comment "FLOW_14"
    ip saddr @meddev_net  drop comment "FLOW_15"
    ip saddr @dmz_net ip daddr @mgmt_net drop comment "FLOW_16"
    ip saddr @internal_net ip daddr @mgmt_net drop comment "FLOW_17"

    log prefix "meddefense-forward-drop: " drop
  }

  chain output {
    type filter hook output priority 0; policy accept;

    ip saddr @dmz_net ip daddr @meddev_net drop comment "OUTPUT_DMZ_MEDDEV_DENY"
    ip saddr @internal_net ip daddr @meddev_net drop comment "OUTPUT_INTERNAL_MEDDEV_DENY"
    ip saddr @meddev_net ip daddr @dmz_net drop comment "OUTPUT_MEDDEV_DMZ_DENY"
    ip saddr @dmz_net ip daddr @mgmt_net drop comment "OUTPUT_DMZ_MGMT_DENY"
    ip saddr @internal_net ip daddr @mgmt_net drop comment "OUTPUT_INTERNAL_MGMT_DENY"

    log prefix "meddefense-output: " counter
  }
}
